### ISSUE TITLE
can this run on a Rapsberry Pi  Zero ?

### ISSUE THREAD

**Issue by deladriere** [padmalcom/jotts#1]
Sorry not an issue but I would like to have a Raspberry Pi  Zero speak German without the need for an Internet connection
(Amazon Polly and IBM Watson have great German voices but are paid service quite complex to install - not to mention the need for a connect and its delays)
I just subscribed to your course (I understand only a bit of German) ;-)
Maybe some of the heavy work can be done on a fast computer but I need the text to speech to be done on the Raspberry Pi ?

**Comment by padmalcom** [comment]
Hi, how about just trying it out? :) I did not test it on a RPi but I currently don't see an issue except the device's performance.

**Comment by deladriere** [comment]
Ok I will run it on my Mac to understand the process ...
