### ISSUE TITLE
Missing additional information in README

### ISSUE THREAD

**Issue by eqikkwkp25-cyber** [padmalcom/jotts#5]
Typo somewhere: The readme says "The synthesizer model has been trained on my voice using Tacotron1." while the releases say "v0.1 Latest Pre-trained German synthesizer model based on tacotron2." 

Can you add more hints how you trained your model(s), i.e. which base repository, data structure and how many hours of your voice you need for the current results?

**Comment by padmalcom** [comment]
Thank you, I fixed the tacotron version typo. You can find training information in my other repository [here](https://github.com/padmalcom/Real-Time-Voice-Cloning-German). As you might know, this is the synthesizer modell. When you have a pretrained model (that you can take from the repo), you need ~15 minutes of your own voice to train a model which imitates your voice well.
