### ISSUE TITLE
Samples of jotts in combination with a modern vocoder like (MB)Melgan, HifiGAN 

### ISSUE THREAD

**Issue by eqikkwkp25-cyber** [padmalcom/jotts#6]
I tried to drop a spectrogram sanmple as npy and feed HifiGAN but it gave me a lot of noise. I am wondering how good your results are, do you have samples with vocoders like above?

**Comment by padmalcom** [comment]
Hi, not for this repository. You can find the entire framework here, that optinally uses MelGAN as vocoder: https://github.com/padmalcom/Real-Time-Voice-Cloning-German

**Comment by eqikkwkp25-cyber** [comment]
In the meantime i tested it with the above framework. The usage of an additional vocoder seems to cost too much inference time for some reasons which i don't know and doesn't give much advantage compared to griffin lim, you are right.
